services:
  redis:
    image: redis:8.2.3
    container_name: redis-server # Optional: Assign a specific container name
#    environment:
#      REDIS_HOST: redis
#      REDIS_PASSWORD: rdp
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379" # Optional: Expose Redis port to the host
#    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres-server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rdp
      POSTGRES_DB: my_db
      volumes:
         postgres_data:/var/lib/postgres
    ports:
    - "5432:5432"

volumes:
    postgres_data:
    redis_data: